#Application Configuration
server:
  port: 8092

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
#spring:
  #h2:
    #console:
      #enabled: true
  # ===============================
  # DB
  # ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerDB
    driverClassName: org.postgresql.Driver
    platform: postgresql
    username: postgres
    password: mauricio29

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"